### ISSUE TITLE
Crash when activating portal while standing inside it

### ISSUE THREAD

**Issue by 5ully** [SuperMartijn642/Wormhole#10]
**Version Info**
- Minecraft, 1.16.4
- Wormhole, 1.1.1

**Steps to Reproduce**
Standing inside portal while activating through the GUI

**Crash report (~/logs/latest.log)**
https://paste.feed-the-beast.com/view/3e652710

**Note
Im gonne guess that the GUI doesnt like the player teleporting away while being open, since the teleport goes through when joining the world on next launch.

**Comment by SuperMartijn642** [comment]
I believe this is fixed in version 1.1.3 already although I'm not quite sure

**Comment by 5ully** [comment]
Sorry if it it was already reported but didnt see it on the closed issue list.

**Comment by SuperMartijn642** [comment]
No it hasn't reported before, I just think updating to 1.1.3 might fix it. Just a guess though since I did fix something somewhat similar.
I will have a proper look at the crash later.

**Comment by 5ully** [comment]
Oki, will see if i can get Sune to update the version on the beta server and get back to you if im still having issues

**Comment by SuperMartijn642** [comment]
It was still happening in 1.1.3 and I fixed it now in 1.1.4.

Thanks for reporting the issue!
